// AUTO-GENERATED by scripts/gen-explore.mjs from sp-explore-manifest.json.
// Every remaining floor viewpoint as a walkable "explore" node. Do not edit by hand.
import type { SakuraNode } from "./nodes";

export const exploreNodes: Record<string, SakuraNode> = {
  "b3-x01": {
    "id": "b3-x01",
    "floor": "B3",
    "image": "b3-x01",
    "blueprint": "blueprint-b3",
    "marker": {
      "x": 10,
      "y": 78
    },
    "nameKey": "areaB3",
    "captionKey": "capB3",
    "view": 1,
    "exits": [
      {
        "to": "b3-platform-mid",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b3-x02",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b3-x02": {
    "id": "b3-x02",
    "floor": "B3",
    "image": "b3-x02",
    "blueprint": "blueprint-b3",
    "marker": {
      "x": 19,
      "y": 70
    },
    "nameKey": "areaB3",
    "captionKey": "capB3",
    "view": 2,
    "exits": [
      {
        "to": "b3-x01",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b3-x03",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b3-x03": {
    "id": "b3-x03",
    "floor": "B3",
    "image": "b3-x03",
    "blueprint": "blueprint-b3",
    "marker": {
      "x": 28,
      "y": 78
    },
    "nameKey": "areaB3",
    "captionKey": "capB3",
    "view": 3,
    "exits": [
      {
        "to": "b3-x02",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b3-x04",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b3-x04": {
    "id": "b3-x04",
    "floor": "B3",
    "image": "b3-x04",
    "blueprint": "blueprint-b3",
    "marker": {
      "x": 37,
      "y": 70
    },
    "nameKey": "areaB3",
    "captionKey": "capB3",
    "view": 4,
    "exits": [
      {
        "to": "b3-x03",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b3-x05",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b3-x05": {
    "id": "b3-x05",
    "floor": "B3",
    "image": "b3-x05",
    "blueprint": "blueprint-b3",
    "marker": {
      "x": 46,
      "y": 78
    },
    "nameKey": "areaB3",
    "captionKey": "capB3",
    "view": 5,
    "exits": [
      {
        "to": "b3-x04",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b3-x06",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b3-x06": {
    "id": "b3-x06",
    "floor": "B3",
    "image": "b3-x06",
    "blueprint": "blueprint-b3",
    "marker": {
      "x": 55,
      "y": 70
    },
    "nameKey": "areaB3",
    "captionKey": "capB3",
    "view": 6,
    "exits": [
      {
        "to": "b3-x05",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b3-x07",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b3-x07": {
    "id": "b3-x07",
    "floor": "B3",
    "image": "b3-x07",
    "blueprint": "blueprint-b3",
    "marker": {
      "x": 64,
      "y": 78
    },
    "nameKey": "areaB3",
    "captionKey": "capB3",
    "view": 7,
    "exits": [
      {
        "to": "b3-x06",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b3-x08",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b3-x08": {
    "id": "b3-x08",
    "floor": "B3",
    "image": "b3-x08",
    "blueprint": "blueprint-b3",
    "marker": {
      "x": 73,
      "y": 70
    },
    "nameKey": "areaB3",
    "captionKey": "capB3",
    "view": 8,
    "exits": [
      {
        "to": "b3-x07",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b3-x09",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b3-x09": {
    "id": "b3-x09",
    "floor": "B3",
    "image": "b3-x09",
    "blueprint": "blueprint-b3",
    "marker": {
      "x": 82,
      "y": 78
    },
    "nameKey": "areaB3",
    "captionKey": "capB3",
    "view": 9,
    "exits": [
      {
        "to": "b3-x08",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b3-x10",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b3-x10": {
    "id": "b3-x10",
    "floor": "B3",
    "image": "b3-x10",
    "blueprint": "blueprint-b3",
    "marker": {
      "x": 10,
      "y": 70
    },
    "nameKey": "areaB3",
    "captionKey": "capB3",
    "view": 10,
    "exits": [
      {
        "to": "b3-x09",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b3-x11",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b3-x11": {
    "id": "b3-x11",
    "floor": "B3",
    "image": "b3-x11",
    "blueprint": "blueprint-b3",
    "marker": {
      "x": 19,
      "y": 78
    },
    "nameKey": "areaB3",
    "captionKey": "capB3",
    "view": 11,
    "exits": [
      {
        "to": "b3-x10",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b3-x12",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b3-x12": {
    "id": "b3-x12",
    "floor": "B3",
    "image": "b3-x12",
    "blueprint": "blueprint-b3",
    "marker": {
      "x": 28,
      "y": 70
    },
    "nameKey": "areaB3",
    "captionKey": "capB3",
    "view": 12,
    "exits": [
      {
        "to": "b3-x11",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b3-x13",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b3-x13": {
    "id": "b3-x13",
    "floor": "B3",
    "image": "b3-x13",
    "blueprint": "blueprint-b3",
    "marker": {
      "x": 37,
      "y": 78
    },
    "nameKey": "areaB3",
    "captionKey": "capB3",
    "view": 13,
    "exits": [
      {
        "to": "b3-x12",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b3-x14",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b3-x14": {
    "id": "b3-x14",
    "floor": "B3",
    "image": "b3-x14",
    "blueprint": "blueprint-b3",
    "marker": {
      "x": 46,
      "y": 70
    },
    "nameKey": "areaB3",
    "captionKey": "capB3",
    "view": 14,
    "exits": [
      {
        "to": "b3-x13",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b3-x15",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b3-x15": {
    "id": "b3-x15",
    "floor": "B3",
    "image": "b3-x15",
    "blueprint": "blueprint-b3",
    "marker": {
      "x": 55,
      "y": 78
    },
    "nameKey": "areaB3",
    "captionKey": "capB3",
    "view": 15,
    "exits": [
      {
        "to": "b3-x14",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b3-x16",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b3-x16": {
    "id": "b3-x16",
    "floor": "B3",
    "image": "b3-x16",
    "blueprint": "blueprint-b3",
    "marker": {
      "x": 64,
      "y": 70
    },
    "nameKey": "areaB3",
    "captionKey": "capB3",
    "view": 16,
    "exits": [
      {
        "to": "b3-x15",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b3-x17",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b3-x17": {
    "id": "b3-x17",
    "floor": "B3",
    "image": "b3-x17",
    "blueprint": "blueprint-b3",
    "marker": {
      "x": 73,
      "y": 78
    },
    "nameKey": "areaB3",
    "captionKey": "capB3",
    "view": 17,
    "exits": [
      {
        "to": "b3-x16",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b3-x18",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b3-x18": {
    "id": "b3-x18",
    "floor": "B3",
    "image": "b3-x18",
    "blueprint": "blueprint-b3",
    "marker": {
      "x": 82,
      "y": 70
    },
    "nameKey": "areaB3",
    "captionKey": "capB3",
    "view": 18,
    "exits": [
      {
        "to": "b3-x17",
        "labelKey": "goBack",
        "dir": "left"
      }
    ]
  },
  "b2-x01": {
    "id": "b2-x01",
    "floor": "B2",
    "image": "b2-x01",
    "blueprint": "blueprint-b2",
    "marker": {
      "x": 10,
      "y": 78
    },
    "nameKey": "areaB2",
    "captionKey": "capB2",
    "view": 1,
    "exits": [
      {
        "to": "b2-concourse",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b2-x02",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b2-x02": {
    "id": "b2-x02",
    "floor": "B2",
    "image": "b2-x02",
    "blueprint": "blueprint-b2",
    "marker": {
      "x": 19,
      "y": 70
    },
    "nameKey": "areaB2",
    "captionKey": "capB2",
    "view": 2,
    "exits": [
      {
        "to": "b2-x01",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b2-x03",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b2-x03": {
    "id": "b2-x03",
    "floor": "B2",
    "image": "b2-x03",
    "blueprint": "blueprint-b2",
    "marker": {
      "x": 28,
      "y": 78
    },
    "nameKey": "areaB2",
    "captionKey": "capB2",
    "view": 3,
    "exits": [
      {
        "to": "b2-x02",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b2-x04",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b2-x04": {
    "id": "b2-x04",
    "floor": "B2",
    "image": "b2-x04",
    "blueprint": "blueprint-b2",
    "marker": {
      "x": 37,
      "y": 70
    },
    "nameKey": "areaB2",
    "captionKey": "capB2",
    "view": 4,
    "exits": [
      {
        "to": "b2-x03",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b2-x05",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b2-x05": {
    "id": "b2-x05",
    "floor": "B2",
    "image": "b2-x05",
    "blueprint": "blueprint-b2",
    "marker": {
      "x": 46,
      "y": 78
    },
    "nameKey": "areaB2",
    "captionKey": "capB2",
    "view": 5,
    "exits": [
      {
        "to": "b2-x04",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b2-x06",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b2-x06": {
    "id": "b2-x06",
    "floor": "B2",
    "image": "b2-x06",
    "blueprint": "blueprint-b2",
    "marker": {
      "x": 55,
      "y": 70
    },
    "nameKey": "areaB2",
    "captionKey": "capB2",
    "view": 6,
    "exits": [
      {
        "to": "b2-x05",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b2-x07",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b2-x07": {
    "id": "b2-x07",
    "floor": "B2",
    "image": "b2-x07",
    "blueprint": "blueprint-b2",
    "marker": {
      "x": 64,
      "y": 78
    },
    "nameKey": "areaB2",
    "captionKey": "capB2",
    "view": 7,
    "exits": [
      {
        "to": "b2-x06",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b2-x08",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b2-x08": {
    "id": "b2-x08",
    "floor": "B2",
    "image": "b2-x08",
    "blueprint": "blueprint-b2",
    "marker": {
      "x": 73,
      "y": 70
    },
    "nameKey": "areaB2",
    "captionKey": "capB2",
    "view": 8,
    "exits": [
      {
        "to": "b2-x07",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b2-x09",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b2-x09": {
    "id": "b2-x09",
    "floor": "B2",
    "image": "b2-x09",
    "blueprint": "blueprint-b2",
    "marker": {
      "x": 82,
      "y": 78
    },
    "nameKey": "areaB2",
    "captionKey": "capB2",
    "view": 9,
    "exits": [
      {
        "to": "b2-x08",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b2-x10",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b2-x10": {
    "id": "b2-x10",
    "floor": "B2",
    "image": "b2-x10",
    "blueprint": "blueprint-b2",
    "marker": {
      "x": 10,
      "y": 70
    },
    "nameKey": "areaB2",
    "captionKey": "capB2",
    "view": 10,
    "exits": [
      {
        "to": "b2-x09",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b2-x11",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b2-x11": {
    "id": "b2-x11",
    "floor": "B2",
    "image": "b2-x11",
    "blueprint": "blueprint-b2",
    "marker": {
      "x": 19,
      "y": 78
    },
    "nameKey": "areaB2",
    "captionKey": "capB2",
    "view": 11,
    "exits": [
      {
        "to": "b2-x10",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b2-x12",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b2-x12": {
    "id": "b2-x12",
    "floor": "B2",
    "image": "b2-x12",
    "blueprint": "blueprint-b2",
    "marker": {
      "x": 28,
      "y": 70
    },
    "nameKey": "areaB2",
    "captionKey": "capB2",
    "view": 12,
    "exits": [
      {
        "to": "b2-x11",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b2-x13",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b2-x13": {
    "id": "b2-x13",
    "floor": "B2",
    "image": "b2-x13",
    "blueprint": "blueprint-b2",
    "marker": {
      "x": 37,
      "y": 78
    },
    "nameKey": "areaB2",
    "captionKey": "capB2",
    "view": 13,
    "exits": [
      {
        "to": "b2-x12",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b2-x14",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b2-x14": {
    "id": "b2-x14",
    "floor": "B2",
    "image": "b2-x14",
    "blueprint": "blueprint-b2",
    "marker": {
      "x": 46,
      "y": 70
    },
    "nameKey": "areaB2",
    "captionKey": "capB2",
    "view": 14,
    "exits": [
      {
        "to": "b2-x13",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b2-x15",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b2-x15": {
    "id": "b2-x15",
    "floor": "B2",
    "image": "b2-x15",
    "blueprint": "blueprint-b2",
    "marker": {
      "x": 55,
      "y": 78
    },
    "nameKey": "areaB2",
    "captionKey": "capB2",
    "view": 15,
    "exits": [
      {
        "to": "b2-x14",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b2-x16",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b2-x16": {
    "id": "b2-x16",
    "floor": "B2",
    "image": "b2-x16",
    "blueprint": "blueprint-b2",
    "marker": {
      "x": 64,
      "y": 70
    },
    "nameKey": "areaB2",
    "captionKey": "capB2",
    "view": 16,
    "exits": [
      {
        "to": "b2-x15",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b2-x17",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b2-x17": {
    "id": "b2-x17",
    "floor": "B2",
    "image": "b2-x17",
    "blueprint": "blueprint-b2",
    "marker": {
      "x": 73,
      "y": 78
    },
    "nameKey": "areaB2",
    "captionKey": "capB2",
    "view": 17,
    "exits": [
      {
        "to": "b2-x16",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b2-x18",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b2-x18": {
    "id": "b2-x18",
    "floor": "B2",
    "image": "b2-x18",
    "blueprint": "blueprint-b2",
    "marker": {
      "x": 82,
      "y": 70
    },
    "nameKey": "areaB2",
    "captionKey": "capB2",
    "view": 18,
    "exits": [
      {
        "to": "b2-x17",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b2-x19",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b2-x19": {
    "id": "b2-x19",
    "floor": "B2",
    "image": "b2-x19",
    "blueprint": "blueprint-b2",
    "marker": {
      "x": 10,
      "y": 78
    },
    "nameKey": "areaB2",
    "captionKey": "capB2",
    "view": 19,
    "exits": [
      {
        "to": "b2-x18",
        "labelKey": "goBack",
        "dir": "left"
      }
    ]
  },
  "b1-x01": {
    "id": "b1-x01",
    "floor": "B1",
    "image": "b1-x01",
    "blueprint": "blueprint-b1",
    "marker": {
      "x": 10,
      "y": 78
    },
    "nameKey": "areaB1",
    "captionKey": "capB1",
    "view": 1,
    "exits": [
      {
        "to": "b1-concourse",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b1-x02",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b1-x02": {
    "id": "b1-x02",
    "floor": "B1",
    "image": "b1-x02",
    "blueprint": "blueprint-b1",
    "marker": {
      "x": 19,
      "y": 70
    },
    "nameKey": "areaB1",
    "captionKey": "capB1",
    "view": 2,
    "exits": [
      {
        "to": "b1-x01",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b1-x03",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b1-x03": {
    "id": "b1-x03",
    "floor": "B1",
    "image": "b1-x03",
    "blueprint": "blueprint-b1",
    "marker": {
      "x": 28,
      "y": 78
    },
    "nameKey": "areaB1",
    "captionKey": "capB1",
    "view": 3,
    "exits": [
      {
        "to": "b1-x02",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b1-x04",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b1-x04": {
    "id": "b1-x04",
    "floor": "B1",
    "image": "b1-x04",
    "blueprint": "blueprint-b1",
    "marker": {
      "x": 37,
      "y": 70
    },
    "nameKey": "areaB1",
    "captionKey": "capB1",
    "view": 4,
    "exits": [
      {
        "to": "b1-x03",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b1-x05",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b1-x05": {
    "id": "b1-x05",
    "floor": "B1",
    "image": "b1-x05",
    "blueprint": "blueprint-b1",
    "marker": {
      "x": 46,
      "y": 78
    },
    "nameKey": "areaB1",
    "captionKey": "capB1",
    "view": 5,
    "exits": [
      {
        "to": "b1-x04",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b1-x06",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b1-x06": {
    "id": "b1-x06",
    "floor": "B1",
    "image": "b1-x06",
    "blueprint": "blueprint-b1",
    "marker": {
      "x": 55,
      "y": 70
    },
    "nameKey": "areaB1",
    "captionKey": "capB1",
    "view": 6,
    "exits": [
      {
        "to": "b1-x05",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b1-x07",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b1-x07": {
    "id": "b1-x07",
    "floor": "B1",
    "image": "b1-x07",
    "blueprint": "blueprint-b1",
    "marker": {
      "x": 64,
      "y": 78
    },
    "nameKey": "areaB1",
    "captionKey": "capB1",
    "view": 7,
    "exits": [
      {
        "to": "b1-x06",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b1-x08",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b1-x08": {
    "id": "b1-x08",
    "floor": "B1",
    "image": "b1-x08",
    "blueprint": "blueprint-b1",
    "marker": {
      "x": 73,
      "y": 70
    },
    "nameKey": "areaB1",
    "captionKey": "capB1",
    "view": 8,
    "exits": [
      {
        "to": "b1-x07",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b1-x09",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b1-x09": {
    "id": "b1-x09",
    "floor": "B1",
    "image": "b1-x09",
    "blueprint": "blueprint-b1",
    "marker": {
      "x": 82,
      "y": 78
    },
    "nameKey": "areaB1",
    "captionKey": "capB1",
    "view": 9,
    "exits": [
      {
        "to": "b1-x08",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b1-x10",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b1-x10": {
    "id": "b1-x10",
    "floor": "B1",
    "image": "b1-x10",
    "blueprint": "blueprint-b1",
    "marker": {
      "x": 10,
      "y": 70
    },
    "nameKey": "areaB1",
    "captionKey": "capB1",
    "view": 10,
    "exits": [
      {
        "to": "b1-x09",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b1-x11",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b1-x11": {
    "id": "b1-x11",
    "floor": "B1",
    "image": "b1-x11",
    "blueprint": "blueprint-b1",
    "marker": {
      "x": 19,
      "y": 78
    },
    "nameKey": "areaB1",
    "captionKey": "capB1",
    "view": 11,
    "exits": [
      {
        "to": "b1-x10",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b1-x12",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b1-x12": {
    "id": "b1-x12",
    "floor": "B1",
    "image": "b1-x12",
    "blueprint": "blueprint-b1",
    "marker": {
      "x": 28,
      "y": 70
    },
    "nameKey": "areaB1",
    "captionKey": "capB1",
    "view": 12,
    "exits": [
      {
        "to": "b1-x11",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b1-x13",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b1-x13": {
    "id": "b1-x13",
    "floor": "B1",
    "image": "b1-x13",
    "blueprint": "blueprint-b1",
    "marker": {
      "x": 37,
      "y": 78
    },
    "nameKey": "areaB1",
    "captionKey": "capB1",
    "view": 13,
    "exits": [
      {
        "to": "b1-x12",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b1-x14",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b1-x14": {
    "id": "b1-x14",
    "floor": "B1",
    "image": "b1-x14",
    "blueprint": "blueprint-b1",
    "marker": {
      "x": 46,
      "y": 70
    },
    "nameKey": "areaB1",
    "captionKey": "capB1",
    "view": 14,
    "exits": [
      {
        "to": "b1-x13",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b1-x15",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b1-x15": {
    "id": "b1-x15",
    "floor": "B1",
    "image": "b1-x15",
    "blueprint": "blueprint-b1",
    "marker": {
      "x": 55,
      "y": 78
    },
    "nameKey": "areaB1",
    "captionKey": "capB1",
    "view": 15,
    "exits": [
      {
        "to": "b1-x14",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b1-x16",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b1-x16": {
    "id": "b1-x16",
    "floor": "B1",
    "image": "b1-x16",
    "blueprint": "blueprint-b1",
    "marker": {
      "x": 64,
      "y": 70
    },
    "nameKey": "areaB1",
    "captionKey": "capB1",
    "view": 16,
    "exits": [
      {
        "to": "b1-x15",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b1-x17",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b1-x17": {
    "id": "b1-x17",
    "floor": "B1",
    "image": "b1-x17",
    "blueprint": "blueprint-b1",
    "marker": {
      "x": 73,
      "y": 78
    },
    "nameKey": "areaB1",
    "captionKey": "capB1",
    "view": 17,
    "exits": [
      {
        "to": "b1-x16",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b1-x18",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b1-x18": {
    "id": "b1-x18",
    "floor": "B1",
    "image": "b1-x18",
    "blueprint": "blueprint-b1",
    "marker": {
      "x": 82,
      "y": 70
    },
    "nameKey": "areaB1",
    "captionKey": "capB1",
    "view": 18,
    "exits": [
      {
        "to": "b1-x17",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "b1-x19",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "b1-x19": {
    "id": "b1-x19",
    "floor": "B1",
    "image": "b1-x19",
    "blueprint": "blueprint-b1",
    "marker": {
      "x": 10,
      "y": 78
    },
    "nameKey": "areaB1",
    "captionKey": "capB1",
    "view": 19,
    "exits": [
      {
        "to": "b1-x18",
        "labelKey": "goBack",
        "dir": "left"
      }
    ]
  },
  "f1-x01": {
    "id": "f1-x01",
    "floor": "1F",
    "image": "f1-x01",
    "blueprint": "blueprint-1f",
    "marker": {
      "x": 10,
      "y": 78
    },
    "nameKey": "areaF1",
    "captionKey": "capF1",
    "view": 1,
    "exits": [
      {
        "to": "f1-concourse-2",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f1-x02",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f1-x02": {
    "id": "f1-x02",
    "floor": "1F",
    "image": "f1-x02",
    "blueprint": "blueprint-1f",
    "marker": {
      "x": 19,
      "y": 70
    },
    "nameKey": "areaF1",
    "captionKey": "capF1",
    "view": 2,
    "exits": [
      {
        "to": "f1-x01",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f1-x03",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f1-x03": {
    "id": "f1-x03",
    "floor": "1F",
    "image": "f1-x03",
    "blueprint": "blueprint-1f",
    "marker": {
      "x": 28,
      "y": 78
    },
    "nameKey": "areaF1",
    "captionKey": "capF1",
    "view": 3,
    "exits": [
      {
        "to": "f1-x02",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f1-x04",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f1-x04": {
    "id": "f1-x04",
    "floor": "1F",
    "image": "f1-x04",
    "blueprint": "blueprint-1f",
    "marker": {
      "x": 37,
      "y": 70
    },
    "nameKey": "areaF1",
    "captionKey": "capF1",
    "view": 4,
    "exits": [
      {
        "to": "f1-x03",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f1-x05",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f1-x05": {
    "id": "f1-x05",
    "floor": "1F",
    "image": "f1-x05",
    "blueprint": "blueprint-1f",
    "marker": {
      "x": 46,
      "y": 78
    },
    "nameKey": "areaF1",
    "captionKey": "capF1",
    "view": 5,
    "exits": [
      {
        "to": "f1-x04",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f1-x06",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f1-x06": {
    "id": "f1-x06",
    "floor": "1F",
    "image": "f1-x06",
    "blueprint": "blueprint-1f",
    "marker": {
      "x": 55,
      "y": 70
    },
    "nameKey": "areaF1",
    "captionKey": "capF1",
    "view": 6,
    "exits": [
      {
        "to": "f1-x05",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f1-x07",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f1-x07": {
    "id": "f1-x07",
    "floor": "1F",
    "image": "f1-x07",
    "blueprint": "blueprint-1f",
    "marker": {
      "x": 64,
      "y": 78
    },
    "nameKey": "areaF1",
    "captionKey": "capF1",
    "view": 7,
    "exits": [
      {
        "to": "f1-x06",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f1-x08",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f1-x08": {
    "id": "f1-x08",
    "floor": "1F",
    "image": "f1-x08",
    "blueprint": "blueprint-1f",
    "marker": {
      "x": 73,
      "y": 70
    },
    "nameKey": "areaF1",
    "captionKey": "capF1",
    "view": 8,
    "exits": [
      {
        "to": "f1-x07",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f1-x09",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f1-x09": {
    "id": "f1-x09",
    "floor": "1F",
    "image": "f1-x09",
    "blueprint": "blueprint-1f",
    "marker": {
      "x": 82,
      "y": 78
    },
    "nameKey": "areaF1",
    "captionKey": "capF1",
    "view": 9,
    "exits": [
      {
        "to": "f1-x08",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f1-x10",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f1-x10": {
    "id": "f1-x10",
    "floor": "1F",
    "image": "f1-x10",
    "blueprint": "blueprint-1f",
    "marker": {
      "x": 10,
      "y": 70
    },
    "nameKey": "areaF1",
    "captionKey": "capF1",
    "view": 10,
    "exits": [
      {
        "to": "f1-x09",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f1-x11",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f1-x11": {
    "id": "f1-x11",
    "floor": "1F",
    "image": "f1-x11",
    "blueprint": "blueprint-1f",
    "marker": {
      "x": 19,
      "y": 78
    },
    "nameKey": "areaF1",
    "captionKey": "capF1",
    "view": 11,
    "exits": [
      {
        "to": "f1-x10",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f1-x12",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f1-x12": {
    "id": "f1-x12",
    "floor": "1F",
    "image": "f1-x12",
    "blueprint": "blueprint-1f",
    "marker": {
      "x": 28,
      "y": 70
    },
    "nameKey": "areaF1",
    "captionKey": "capF1",
    "view": 12,
    "exits": [
      {
        "to": "f1-x11",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f1-x13",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f1-x13": {
    "id": "f1-x13",
    "floor": "1F",
    "image": "f1-x13",
    "blueprint": "blueprint-1f",
    "marker": {
      "x": 37,
      "y": 78
    },
    "nameKey": "areaF1",
    "captionKey": "capF1",
    "view": 13,
    "exits": [
      {
        "to": "f1-x12",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f1-x14",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f1-x14": {
    "id": "f1-x14",
    "floor": "1F",
    "image": "f1-x14",
    "blueprint": "blueprint-1f",
    "marker": {
      "x": 46,
      "y": 70
    },
    "nameKey": "areaF1",
    "captionKey": "capF1",
    "view": 14,
    "exits": [
      {
        "to": "f1-x13",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f1-x15",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f1-x15": {
    "id": "f1-x15",
    "floor": "1F",
    "image": "f1-x15",
    "blueprint": "blueprint-1f",
    "marker": {
      "x": 55,
      "y": 78
    },
    "nameKey": "areaF1",
    "captionKey": "capF1",
    "view": 15,
    "exits": [
      {
        "to": "f1-x14",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f1-x16",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f1-x16": {
    "id": "f1-x16",
    "floor": "1F",
    "image": "f1-x16",
    "blueprint": "blueprint-1f",
    "marker": {
      "x": 64,
      "y": 70
    },
    "nameKey": "areaF1",
    "captionKey": "capF1",
    "view": 16,
    "exits": [
      {
        "to": "f1-x15",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f1-x17",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f1-x17": {
    "id": "f1-x17",
    "floor": "1F",
    "image": "f1-x17",
    "blueprint": "blueprint-1f",
    "marker": {
      "x": 73,
      "y": 78
    },
    "nameKey": "areaF1",
    "captionKey": "capF1",
    "view": 17,
    "exits": [
      {
        "to": "f1-x16",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f1-x18",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f1-x18": {
    "id": "f1-x18",
    "floor": "1F",
    "image": "f1-x18",
    "blueprint": "blueprint-1f",
    "marker": {
      "x": 82,
      "y": 70
    },
    "nameKey": "areaF1",
    "captionKey": "capF1",
    "view": 18,
    "exits": [
      {
        "to": "f1-x17",
        "labelKey": "goBack",
        "dir": "left"
      }
    ]
  },
  "f2-x01": {
    "id": "f2-x01",
    "floor": "2F",
    "image": "f2-x01",
    "blueprint": "blueprint-2f",
    "marker": {
      "x": 10,
      "y": 78
    },
    "nameKey": "areaF2",
    "captionKey": "capF2",
    "view": 1,
    "exits": [
      {
        "to": "f2-concourse-2",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f2-x02",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f2-x02": {
    "id": "f2-x02",
    "floor": "2F",
    "image": "f2-x02",
    "blueprint": "blueprint-2f",
    "marker": {
      "x": 19,
      "y": 70
    },
    "nameKey": "areaF2",
    "captionKey": "capF2",
    "view": 2,
    "exits": [
      {
        "to": "f2-x01",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f2-x03",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f2-x03": {
    "id": "f2-x03",
    "floor": "2F",
    "image": "f2-x03",
    "blueprint": "blueprint-2f",
    "marker": {
      "x": 28,
      "y": 78
    },
    "nameKey": "areaF2",
    "captionKey": "capF2",
    "view": 3,
    "exits": [
      {
        "to": "f2-x02",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f2-x04",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f2-x04": {
    "id": "f2-x04",
    "floor": "2F",
    "image": "f2-x04",
    "blueprint": "blueprint-2f",
    "marker": {
      "x": 37,
      "y": 70
    },
    "nameKey": "areaF2",
    "captionKey": "capF2",
    "view": 4,
    "exits": [
      {
        "to": "f2-x03",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f2-x05",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f2-x05": {
    "id": "f2-x05",
    "floor": "2F",
    "image": "f2-x05",
    "blueprint": "blueprint-2f",
    "marker": {
      "x": 46,
      "y": 78
    },
    "nameKey": "areaF2",
    "captionKey": "capF2",
    "view": 5,
    "exits": [
      {
        "to": "f2-x04",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f2-x06",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f2-x06": {
    "id": "f2-x06",
    "floor": "2F",
    "image": "f2-x06",
    "blueprint": "blueprint-2f",
    "marker": {
      "x": 55,
      "y": 70
    },
    "nameKey": "areaF2",
    "captionKey": "capF2",
    "view": 6,
    "exits": [
      {
        "to": "f2-x05",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f2-x07",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f2-x07": {
    "id": "f2-x07",
    "floor": "2F",
    "image": "f2-x07",
    "blueprint": "blueprint-2f",
    "marker": {
      "x": 64,
      "y": 78
    },
    "nameKey": "areaF2",
    "captionKey": "capF2",
    "view": 7,
    "exits": [
      {
        "to": "f2-x06",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f2-x08",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f2-x08": {
    "id": "f2-x08",
    "floor": "2F",
    "image": "f2-x08",
    "blueprint": "blueprint-2f",
    "marker": {
      "x": 73,
      "y": 70
    },
    "nameKey": "areaF2",
    "captionKey": "capF2",
    "view": 8,
    "exits": [
      {
        "to": "f2-x07",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f2-x09",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f2-x09": {
    "id": "f2-x09",
    "floor": "2F",
    "image": "f2-x09",
    "blueprint": "blueprint-2f",
    "marker": {
      "x": 82,
      "y": 78
    },
    "nameKey": "areaF2",
    "captionKey": "capF2",
    "view": 9,
    "exits": [
      {
        "to": "f2-x08",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f2-x10",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f2-x10": {
    "id": "f2-x10",
    "floor": "2F",
    "image": "f2-x10",
    "blueprint": "blueprint-2f",
    "marker": {
      "x": 10,
      "y": 70
    },
    "nameKey": "areaF2",
    "captionKey": "capF2",
    "view": 10,
    "exits": [
      {
        "to": "f2-x09",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f2-x11",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f2-x11": {
    "id": "f2-x11",
    "floor": "2F",
    "image": "f2-x11",
    "blueprint": "blueprint-2f",
    "marker": {
      "x": 19,
      "y": 78
    },
    "nameKey": "areaF2",
    "captionKey": "capF2",
    "view": 11,
    "exits": [
      {
        "to": "f2-x10",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f2-x12",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f2-x12": {
    "id": "f2-x12",
    "floor": "2F",
    "image": "f2-x12",
    "blueprint": "blueprint-2f",
    "marker": {
      "x": 28,
      "y": 70
    },
    "nameKey": "areaF2",
    "captionKey": "capF2",
    "view": 12,
    "exits": [
      {
        "to": "f2-x11",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f2-x13",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f2-x13": {
    "id": "f2-x13",
    "floor": "2F",
    "image": "f2-x13",
    "blueprint": "blueprint-2f",
    "marker": {
      "x": 37,
      "y": 78
    },
    "nameKey": "areaF2",
    "captionKey": "capF2",
    "view": 13,
    "exits": [
      {
        "to": "f2-x12",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f2-x14",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f2-x14": {
    "id": "f2-x14",
    "floor": "2F",
    "image": "f2-x14",
    "blueprint": "blueprint-2f",
    "marker": {
      "x": 46,
      "y": 70
    },
    "nameKey": "areaF2",
    "captionKey": "capF2",
    "view": 14,
    "exits": [
      {
        "to": "f2-x13",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f2-x15",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f2-x15": {
    "id": "f2-x15",
    "floor": "2F",
    "image": "f2-x15",
    "blueprint": "blueprint-2f",
    "marker": {
      "x": 55,
      "y": 78
    },
    "nameKey": "areaF2",
    "captionKey": "capF2",
    "view": 15,
    "exits": [
      {
        "to": "f2-x14",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f2-x16",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f2-x16": {
    "id": "f2-x16",
    "floor": "2F",
    "image": "f2-x16",
    "blueprint": "blueprint-2f",
    "marker": {
      "x": 64,
      "y": 70
    },
    "nameKey": "areaF2",
    "captionKey": "capF2",
    "view": 16,
    "exits": [
      {
        "to": "f2-x15",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f2-x17",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f2-x17": {
    "id": "f2-x17",
    "floor": "2F",
    "image": "f2-x17",
    "blueprint": "blueprint-2f",
    "marker": {
      "x": 73,
      "y": 78
    },
    "nameKey": "areaF2",
    "captionKey": "capF2",
    "view": 17,
    "exits": [
      {
        "to": "f2-x16",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f2-x18",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f2-x18": {
    "id": "f2-x18",
    "floor": "2F",
    "image": "f2-x18",
    "blueprint": "blueprint-2f",
    "marker": {
      "x": 82,
      "y": 70
    },
    "nameKey": "areaF2",
    "captionKey": "capF2",
    "view": 18,
    "exits": [
      {
        "to": "f2-x17",
        "labelKey": "goBack",
        "dir": "left"
      }
    ]
  },
  "f3-x01": {
    "id": "f3-x01",
    "floor": "3F",
    "image": "f3-x01",
    "blueprint": "blueprint-3f",
    "marker": {
      "x": 10,
      "y": 78
    },
    "nameKey": "areaF3",
    "captionKey": "capF3",
    "view": 1,
    "exits": [
      {
        "to": "f3-northdeck",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f3-x02",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f3-x02": {
    "id": "f3-x02",
    "floor": "3F",
    "image": "f3-x02",
    "blueprint": "blueprint-3f",
    "marker": {
      "x": 19,
      "y": 70
    },
    "nameKey": "areaF3",
    "captionKey": "capF3",
    "view": 2,
    "exits": [
      {
        "to": "f3-x01",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f3-x03",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f3-x03": {
    "id": "f3-x03",
    "floor": "3F",
    "image": "f3-x03",
    "blueprint": "blueprint-3f",
    "marker": {
      "x": 28,
      "y": 78
    },
    "nameKey": "areaF3",
    "captionKey": "capF3",
    "view": 3,
    "exits": [
      {
        "to": "f3-x02",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f3-x04",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f3-x04": {
    "id": "f3-x04",
    "floor": "3F",
    "image": "f3-x04",
    "blueprint": "blueprint-3f",
    "marker": {
      "x": 37,
      "y": 70
    },
    "nameKey": "areaF3",
    "captionKey": "capF3",
    "view": 4,
    "exits": [
      {
        "to": "f3-x03",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f3-x05",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f3-x05": {
    "id": "f3-x05",
    "floor": "3F",
    "image": "f3-x05",
    "blueprint": "blueprint-3f",
    "marker": {
      "x": 46,
      "y": 78
    },
    "nameKey": "areaF3",
    "captionKey": "capF3",
    "view": 5,
    "exits": [
      {
        "to": "f3-x04",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f3-x06",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f3-x06": {
    "id": "f3-x06",
    "floor": "3F",
    "image": "f3-x06",
    "blueprint": "blueprint-3f",
    "marker": {
      "x": 55,
      "y": 70
    },
    "nameKey": "areaF3",
    "captionKey": "capF3",
    "view": 6,
    "exits": [
      {
        "to": "f3-x05",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f3-x07",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f3-x07": {
    "id": "f3-x07",
    "floor": "3F",
    "image": "f3-x07",
    "blueprint": "blueprint-3f",
    "marker": {
      "x": 64,
      "y": 78
    },
    "nameKey": "areaF3",
    "captionKey": "capF3",
    "view": 7,
    "exits": [
      {
        "to": "f3-x06",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f3-x08",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f3-x08": {
    "id": "f3-x08",
    "floor": "3F",
    "image": "f3-x08",
    "blueprint": "blueprint-3f",
    "marker": {
      "x": 73,
      "y": 70
    },
    "nameKey": "areaF3",
    "captionKey": "capF3",
    "view": 8,
    "exits": [
      {
        "to": "f3-x07",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f3-x09",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f3-x09": {
    "id": "f3-x09",
    "floor": "3F",
    "image": "f3-x09",
    "blueprint": "blueprint-3f",
    "marker": {
      "x": 82,
      "y": 78
    },
    "nameKey": "areaF3",
    "captionKey": "capF3",
    "view": 9,
    "exits": [
      {
        "to": "f3-x08",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f3-x10",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f3-x10": {
    "id": "f3-x10",
    "floor": "3F",
    "image": "f3-x10",
    "blueprint": "blueprint-3f",
    "marker": {
      "x": 10,
      "y": 70
    },
    "nameKey": "areaF3",
    "captionKey": "capF3",
    "view": 10,
    "exits": [
      {
        "to": "f3-x09",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f3-x11",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f3-x11": {
    "id": "f3-x11",
    "floor": "3F",
    "image": "f3-x11",
    "blueprint": "blueprint-3f",
    "marker": {
      "x": 19,
      "y": 78
    },
    "nameKey": "areaF3",
    "captionKey": "capF3",
    "view": 11,
    "exits": [
      {
        "to": "f3-x10",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f3-x12",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f3-x12": {
    "id": "f3-x12",
    "floor": "3F",
    "image": "f3-x12",
    "blueprint": "blueprint-3f",
    "marker": {
      "x": 28,
      "y": 70
    },
    "nameKey": "areaF3",
    "captionKey": "capF3",
    "view": 12,
    "exits": [
      {
        "to": "f3-x11",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f3-x13",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f3-x13": {
    "id": "f3-x13",
    "floor": "3F",
    "image": "f3-x13",
    "blueprint": "blueprint-3f",
    "marker": {
      "x": 37,
      "y": 78
    },
    "nameKey": "areaF3",
    "captionKey": "capF3",
    "view": 13,
    "exits": [
      {
        "to": "f3-x12",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f3-x14",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f3-x14": {
    "id": "f3-x14",
    "floor": "3F",
    "image": "f3-x14",
    "blueprint": "blueprint-3f",
    "marker": {
      "x": 46,
      "y": 70
    },
    "nameKey": "areaF3",
    "captionKey": "capF3",
    "view": 14,
    "exits": [
      {
        "to": "f3-x13",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f3-x15",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f3-x15": {
    "id": "f3-x15",
    "floor": "3F",
    "image": "f3-x15",
    "blueprint": "blueprint-3f",
    "marker": {
      "x": 55,
      "y": 78
    },
    "nameKey": "areaF3",
    "captionKey": "capF3",
    "view": 15,
    "exits": [
      {
        "to": "f3-x14",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f3-x16",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f3-x16": {
    "id": "f3-x16",
    "floor": "3F",
    "image": "f3-x16",
    "blueprint": "blueprint-3f",
    "marker": {
      "x": 64,
      "y": 70
    },
    "nameKey": "areaF3",
    "captionKey": "capF3",
    "view": 16,
    "exits": [
      {
        "to": "f3-x15",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f3-x17",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f3-x17": {
    "id": "f3-x17",
    "floor": "3F",
    "image": "f3-x17",
    "blueprint": "blueprint-3f",
    "marker": {
      "x": 73,
      "y": 78
    },
    "nameKey": "areaF3",
    "captionKey": "capF3",
    "view": 17,
    "exits": [
      {
        "to": "f3-x16",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f3-x18",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f3-x18": {
    "id": "f3-x18",
    "floor": "3F",
    "image": "f3-x18",
    "blueprint": "blueprint-3f",
    "marker": {
      "x": 82,
      "y": 70
    },
    "nameKey": "areaF3",
    "captionKey": "capF3",
    "view": 18,
    "exits": [
      {
        "to": "f3-x17",
        "labelKey": "goBack",
        "dir": "left"
      }
    ]
  },
  "f4-x01": {
    "id": "f4-x01",
    "floor": "4F",
    "image": "f4-x01",
    "blueprint": "blueprint-4f",
    "marker": {
      "x": 10,
      "y": 78
    },
    "nameKey": "areaF4",
    "captionKey": "capF4",
    "view": 1,
    "exits": [
      {
        "to": "f4-sky-garden",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f4-x02",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f4-x02": {
    "id": "f4-x02",
    "floor": "4F",
    "image": "f4-x02",
    "blueprint": "blueprint-4f",
    "marker": {
      "x": 19,
      "y": 70
    },
    "nameKey": "areaF4",
    "captionKey": "capF4",
    "view": 2,
    "exits": [
      {
        "to": "f4-x01",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f4-x03",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f4-x03": {
    "id": "f4-x03",
    "floor": "4F",
    "image": "f4-x03",
    "blueprint": "blueprint-4f",
    "marker": {
      "x": 28,
      "y": 78
    },
    "nameKey": "areaF4",
    "captionKey": "capF4",
    "view": 3,
    "exits": [
      {
        "to": "f4-x02",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f4-x04",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f4-x04": {
    "id": "f4-x04",
    "floor": "4F",
    "image": "f4-x04",
    "blueprint": "blueprint-4f",
    "marker": {
      "x": 37,
      "y": 70
    },
    "nameKey": "areaF4",
    "captionKey": "capF4",
    "view": 4,
    "exits": [
      {
        "to": "f4-x03",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f4-x05",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f4-x05": {
    "id": "f4-x05",
    "floor": "4F",
    "image": "f4-x05",
    "blueprint": "blueprint-4f",
    "marker": {
      "x": 46,
      "y": 78
    },
    "nameKey": "areaF4",
    "captionKey": "capF4",
    "view": 5,
    "exits": [
      {
        "to": "f4-x04",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f4-x06",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f4-x06": {
    "id": "f4-x06",
    "floor": "4F",
    "image": "f4-x06",
    "blueprint": "blueprint-4f",
    "marker": {
      "x": 55,
      "y": 70
    },
    "nameKey": "areaF4",
    "captionKey": "capF4",
    "view": 6,
    "exits": [
      {
        "to": "f4-x05",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f4-x07",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f4-x07": {
    "id": "f4-x07",
    "floor": "4F",
    "image": "f4-x07",
    "blueprint": "blueprint-4f",
    "marker": {
      "x": 64,
      "y": 78
    },
    "nameKey": "areaF4",
    "captionKey": "capF4",
    "view": 7,
    "exits": [
      {
        "to": "f4-x06",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f4-x08",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f4-x08": {
    "id": "f4-x08",
    "floor": "4F",
    "image": "f4-x08",
    "blueprint": "blueprint-4f",
    "marker": {
      "x": 73,
      "y": 70
    },
    "nameKey": "areaF4",
    "captionKey": "capF4",
    "view": 8,
    "exits": [
      {
        "to": "f4-x07",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f4-x09",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f4-x09": {
    "id": "f4-x09",
    "floor": "4F",
    "image": "f4-x09",
    "blueprint": "blueprint-4f",
    "marker": {
      "x": 82,
      "y": 78
    },
    "nameKey": "areaF4",
    "captionKey": "capF4",
    "view": 9,
    "exits": [
      {
        "to": "f4-x08",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f4-x10",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f4-x10": {
    "id": "f4-x10",
    "floor": "4F",
    "image": "f4-x10",
    "blueprint": "blueprint-4f",
    "marker": {
      "x": 10,
      "y": 70
    },
    "nameKey": "areaF4",
    "captionKey": "capF4",
    "view": 10,
    "exits": [
      {
        "to": "f4-x09",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f4-x11",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f4-x11": {
    "id": "f4-x11",
    "floor": "4F",
    "image": "f4-x11",
    "blueprint": "blueprint-4f",
    "marker": {
      "x": 19,
      "y": 78
    },
    "nameKey": "areaF4",
    "captionKey": "capF4",
    "view": 11,
    "exits": [
      {
        "to": "f4-x10",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f4-x12",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f4-x12": {
    "id": "f4-x12",
    "floor": "4F",
    "image": "f4-x12",
    "blueprint": "blueprint-4f",
    "marker": {
      "x": 28,
      "y": 70
    },
    "nameKey": "areaF4",
    "captionKey": "capF4",
    "view": 12,
    "exits": [
      {
        "to": "f4-x11",
        "labelKey": "goBack",
        "dir": "left"
      },
      {
        "to": "f4-x13",
        "labelKey": "goRight",
        "dir": "right"
      }
    ]
  },
  "f4-x13": {
    "id": "f4-x13",
    "floor": "4F",
    "image": "f4-x13",
    "blueprint": "blueprint-4f",
    "marker": {
      "x": 37,
      "y": 78
    },
    "nameKey": "areaF4",
    "captionKey": "capF4",
    "view": 13,
    "exits": [
      {
        "to": "f4-x12",
        "labelKey": "goBack",
        "dir": "left"
      }
    ]
  }
};

export const exploreHubLinks: Array<{ hub: string; to: string; dir: "up" | "down" | "left" | "right" }> = [
  {
    "hub": "b3-platform-mid",
    "to": "b3-x01",
    "dir": "down"
  },
  {
    "hub": "b2-concourse",
    "to": "b2-x01",
    "dir": "down"
  },
  {
    "hub": "b1-concourse",
    "to": "b1-x01",
    "dir": "down"
  },
  {
    "hub": "f1-concourse-2",
    "to": "f1-x01",
    "dir": "down"
  },
  {
    "hub": "f2-concourse-2",
    "to": "f2-x01",
    "dir": "down"
  },
  {
    "hub": "f3-northdeck",
    "to": "f3-x01",
    "dir": "left"
  },
  {
    "hub": "f4-sky-garden",
    "to": "f4-x01",
    "dir": "right"
  }
];
