#!/usr/bin/env node
/**
 * Emits data/station-practice/sakura/explore.ts from the explore manifest:
 * every remaining floor viewpoint becomes a walkable "explore" node, chained
 * left/right per floor, with the chain head linking back to that floor's hub
 * (a curated node). Lets the player wander every image on every floor.
 */
import fs from "node:fs";
import path from "node:path";

const manifest = JSON.parse(fs.readFileSync(path.join("scripts", "station-practice", "sp-explore-manifest.json"), "utf8"));

const FLOORS = {
  b3: { label: "B3", blueprint: "blueprint-b3", hub: "b3-platform-mid", dir: "down" },
  b2: { label: "B2", blueprint: "blueprint-b2", hub: "b2-concourse", dir: "down" },
  b1: { label: "B1", blueprint: "blueprint-b1", hub: "b1-concourse", dir: "down" },
  f1: { label: "1F", blueprint: "blueprint-1f", hub: "f1-concourse-2", dir: "down" },
  f2: { label: "2F", blueprint: "blueprint-2f", hub: "f2-concourse-2", dir: "down" },
  f3: { label: "3F", blueprint: "blueprint-3f", hub: "f3-northdeck", dir: "left" },
  f4: { label: "4F", blueprint: "blueprint-4f", hub: "f4-sky-garden", dir: "right" },
};

const cap = (c) => c[0].toUpperCase() + c.slice(1);
const nodes = [];
const hubs = [];

for (const [code, cfg] of Object.entries(FLOORS)) {
  const list = manifest[code] || [];
  if (!list.length) continue;
  hubs.push({ hub: cfg.hub, to: list[0], dir: cfg.dir });
  list.forEach((img, i) => {
    const prev = i === 0 ? cfg.hub : list[i - 1];
    const exits = [{ to: prev, labelKey: "goBack", dir: "left" }];
    if (i < list.length - 1) exits.push({ to: list[i + 1], labelKey: "goRight", dir: "right" });
    nodes.push({
      id: img,
      floor: cfg.label,
      image: img,
      blueprint: cfg.blueprint,
      marker: { x: 10 + (i % 9) * 9, y: 78 - (i % 2) * 8 },
      nameKey: "area" + cap(code),
      captionKey: "cap" + cap(code),
      view: i + 1,
      exits,
    });
  });
}

const body = `// AUTO-GENERATED by scripts/gen-explore.mjs from sp-explore-manifest.json.
// Every remaining floor viewpoint as a walkable "explore" node. Do not edit by hand.
import type { SakuraNode } from "./nodes";

export const exploreNodes: Record<string, SakuraNode> = ${JSON.stringify(
    Object.fromEntries(nodes.map((n) => [n.id, n])),
    null,
    2,
  )};

export const exploreHubLinks: Array<{ hub: string; to: string; dir: "up" | "down" | "left" | "right" }> = ${JSON.stringify(
    hubs,
    null,
    2,
  )};
`;

fs.writeFileSync(path.join("data", "station-practice", "sakura", "explore.ts"), body);
console.log(`wrote explore.ts: ${nodes.length} explore nodes, ${hubs.length} hub links`);
